parameters:
#    lykion_lykion.example.class: Lykion\LykionBundle\Example

services:
#    lykion_lykion.example:
#        class: %lykion_lykion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
